### ISSUE TITLE
Iron Scripter #1 Comments

### ISSUE THREAD

**Issue by jdhitsolutions** [jddemcher/supreme-octo-chainsaw#1]
The challenge is to write a command that will take input from Get-Counter and write out a more user friendly object. Your command is running Get-Counter. Ideally your function will consume the results of any Get-Counter command regardless of counter set. 

You might also reconsider the name. It is not typical to include a dash in the noun. 

Otherwise, you are on a good track to break a part the counter object and re-assemble into something else.

**Comment by jddemcher** [comment]
@jdhitsolutions - thanks for the clarification! I did misunderstand the challenge, and believe I have addressed the issue. Looking forward to more challenges!
